Start to add support for Electra
attestantio/go-builder-client pull request #27
Opened 2024-05-06 19:09 UTC by jtraglia

This PR begins to adds support for Electra. It does not include tests. It goes along with this PR:
* https://github.com/attestantio/go-eth2-client/pull/131

2024-05-06 22:01 UTC, mcdee requested changes
One change necessary, the rest looks good.

2024-05-06 22:03 UTC, jtraglia commented on go.mod
> +	github.com/goccy/go-yaml v1.11.3
Oops, will downgrade that. Not sure how that happened.

2024-05-07 00:27 UTC, jtraglia commented on go.mod
> +	github.com/goccy/go-yaml v1.11.3
Fixed. Running `go mod tidy` auto-upgraded that package.

2024-05-07 07:39 UTC, mcdee approved these changes

2024-05-07 07:41 UTC, merged